@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.jsonthings.things.serializers;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;