@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.jsonthings.things.events;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;