@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.jsonthings.things.enchantments;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;