@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.jsonthings.things;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;