@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.jsonthings.things;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;