@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.jsonthings.things.properties;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;