@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.jsonthings.things.serializers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;