@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.jsonthings.things.shapes;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;