@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.jsonthings.things.builders;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;