@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.jsonthings.things.builders;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;